name: Code Review
on: pull_request
jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set execute permission on code-review.sh
        run: chmod +x code-review.sh
      - name: Run code review
        run: npm run code-review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
