name: Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Code Review
        uses: ./.github/actions/code-review
        with:
          PROGRAMMING_LANGUAGE: 'JavaScript'
          REVIEW_COMMENT_PREFIX: 'chatgpt:'
          FULL_REVIEW_COMMENT: 'chatgpt'
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}